#!/usr/bin/env bash

show_menu() {
    echo 'Screenshoot selection'
    echo 'Screenshoot selection timeout (5s)'
    echo 'Screenshoot'
    echo 'Screenshoot timeout (5s)'
}

copy_to_clipboard() {
    echo xclip -selection clipboard -t image/png -i "$1"
    xclip -selection clipboard -t image/png -i "$1"
}

main() {
    # create directory
    OUTPUT_DIR=${HOME}/screenshoot
    oldpwd=$(pwd)
    mkdir -p ${OUTPUT_DIR}
    cd ${OUTPUT_DIR}

    choice=$(show_menu | rofi -dmenu -i -fuzzy -p "scrot ($OUTPUT_DIR)")

    echo "$choice"

    case "$choice" in
        'Screenshoot selection')
            output=$(scrot -ps -e 'echo "\$(pwd)/$f"')
            notify-send "Saved $output"
            copy_to_clipboard "$output"
            ;;
        'Screenshoot selection timeout (5s)')
            notify-send 'running scrot -s -d 5'
            output=$(scrot -ps -d 5s -e 'echo "\$(pwd)/$f"')
            notify-send "Saved \$(pwd)/$f"
            copy_to_clipboard "$output"
            ;;
        'Screenshoot')
            output=$(scrot -e 'echo "\$(pwd)/$f"')
            notify-send "Saved \$(pwd)/$f"
            copy_to_clipboard "$output"
            ;;
        'Screenshoot timeout (5s)')
            notify-send 'running scrot -d 5'
            output=$(scrot -d 5 -e 'echo "\$(pwd)/$f"')
            notify-send "Saved \$(pwd)/$f"
            copy_to_clipboard "$output"
            ;;
        *)
            ;;
    esac

    cd ${oldpwd}
}


main
