#!/usr/bin/env bash

LAST_FILE=''
SCROOT_LAST_FILE=/tmp/scroot_last_file

show_menu() {
    echo 'Screenshoot selection'
    echo 'Screenshoot selection timeout (5s)'
    echo 'Screenshoot'
    echo 'Screenshoot timeout (5s)'
}

copy_to_clipboard() {
    echo xclip -selection clipboard -t image/png -i "$1"
    xclip -selection clipboard -t image/png -i "$1"
}

edit_clipboard() {
    input_file=$(cat $SCROOT_LAST_FILE)
    if [[ -f "$input_file" ]] ; then
        # use xdg-open
        /usr/bin/kolourpaint "$input_file"
    fi
}

main() {
    case "$1" in
        e|edit)
            edit_clipboard
            exit
            ;;
    esac

    # create directory
    OUTPUT_DIR=${HOME}/screenshoot
    oldpwd=$(pwd)
    mkdir -p ${OUTPUT_DIR}
    cd ${OUTPUT_DIR}

    choice=$(show_menu | rofi -dmenu -i -fuzzy -p "scrot ($OUTPUT_DIR)")

    echo "$choice"

    case "$choice" in
        'Screenshoot selection')
            LAST_FILE=$(scrot -ps -d 0.5s -e 'echo "\$(pwd)/$f"')
            notify-send "Saved $LAST_FILE"
            copy_to_clipboard "$LAST_FILE"
            ;;
        'Screenshoot selection timeout (5s)')
            notify-send 'running scrot -s -d 5'
            LAST_FILE=$(scrot -ps -d 5s -e 'echo "\$(pwd)/$f"')
            notify-send "Saved $LAST_FILE"
            copy_to_clipboard "$LAST_FILE"
            ;;
        'Screenshoot')
            LAST_FILE=$(scrot -e 'echo "\$(pwd)/$f"')
            notify-send "Saved $LAST_FILE"
            copy_to_clipboard "$LAST_FILE"
            ;;
        'Screenshoot timeout (5s)')
            notify-send 'running scrot -d 5'
            LAST_FILE=$(scrot -d 5 -e 'echo "\$(pwd)/$f"')
            notify-send "Saved $LAST_FILE"
            copy_to_clipboard "$LAST_FILE"
            ;;
        *)
            # notify-send 'kosong'
            ;;
    esac

    [[ "x$LAST_FILE" == "x" ]] || echo $LAST_FILE > $SCROOT_LAST_FILE

    cd ${oldpwd}
}


main $*
