#!/usr/bin/env bash

LAST_FILE=''
SCROOT_LAST_FILE=/tmp/scroot_last_file
SCROOT_LAST_FILE_UPLOAD=/tmp/scroot_last_file_upload

show_menu() {
    echo 'Screenshoot selection'
    echo 'Screenshoot selection timeout (5s)'
    echo 'Screenshoot'
    echo 'Screenshoot timeout (5s)'
    echo 'Copy last file to clipboard'
    echo 'Copy last file path to clipboard'
    echo 'Copy last link to clipboard'
    echo 'Upload last file to imgur'
}

copy_to_clipboard() {
    echo xclip -selection clipboard -t image/png -i "$1"
    xclip -selection clipboard -t image/png -i "$1"
}

edit_clipboard() {
    input_file=$(cat $SCROOT_LAST_FILE)
    if [[ -f "$input_file" ]] ; then
        # use xdg-open
        /usr/bin/kolourpaint "$input_file"
    fi
}

get_last_link() {
    sed -rn 's/.*link":"([^"]+)".*$/\1/p' $SCROOT_LAST_FILE_UPLOAD
}

to_imgurl_clipboard() {
    input_file=$(cat $SCROOT_LAST_FILE)
    if [[ -f "$input_file" ]] ; then
        # TODO: prevent same file upload
        curl -q -X POST "https://api.imgur.com/3/upload" -F "image=@$input_file" -o $SCROOT_LAST_FILE_UPLOAD
        # copy link to clipboar
        imgurl_link=$(get_last_link)
        echo $imgurl_link| xclip -sel c
        notify-send "$imgurl_link"
    fi
}

main() {
    case "$1" in
        e|edit)
            edit_clipboard
            exit
            ;;
        u|upload)
            to_imgurl_clipboard
            exit
            ;;
    esac

    # create directory
    OUTPUT_DIR=${HOME}/screenshoot
    oldpwd=$(pwd)
    mkdir -p ${OUTPUT_DIR}
    cd ${OUTPUT_DIR}

    choice=$(show_menu | rofi -dmenu -i -fuzzy -p "scrot ($OUTPUT_DIR)")

    echo "$choice"

    case "$choice" in
        'Screenshoot selection')
            LAST_FILE=$(scrot -ps -d 0.5s -e 'echo "\$(pwd)/$f"')
            notify-send "Saved $LAST_FILE"
            copy_to_clipboard "$LAST_FILE"
            ;;
        'Screenshoot selection timeout (5s)')
            notify-send 'running scrot -s -d 5'
            LAST_FILE=$(scrot -ps -d 5s -e 'echo "\$(pwd)/$f"')
            notify-send "Saved $LAST_FILE"
            copy_to_clipboard "$LAST_FILE"
            ;;
        'Screenshoot')
            LAST_FILE=$(scrot -e 'echo "\$(pwd)/$f"')
            notify-send "Saved $LAST_FILE"
            copy_to_clipboard "$LAST_FILE"
            ;;
        'Screenshoot timeout (5s)')
            notify-send 'running scrot -d 5'
            LAST_FILE=$(scrot -d 5 -e 'echo "\$(pwd)/$f"')
            notify-send "Saved $LAST_FILE"
            copy_to_clipboard "$LAST_FILE"
            ;;
        'Copy last file to clipboard')
            input_file=$(cat $SCROOT_LAST_FILE)
            mime=$(file -i $input_file | awk '{print $2}' | tr -d ';')
            xclip -selection clipboard -t "$mime" -i "$input_file"
            ;;
        'Copy last file path to clipboard')
            cat $SCROOT_LAST_FILE | xclip -sel c
            ;;
        'Copy last link to clipboard')
            get_last_link | xclip -sel c
            ;;
        'Upload last file to imgur')
            to_imgurl_clipboard
            ;;
        *)
            # notify-send 'kosong'
            ;;
    esac

    [[ "x$LAST_FILE" == "x" ]] || echo $LAST_FILE > $SCROOT_LAST_FILE

    cd ${oldpwd}
}


main $*
