#!/usr/bin/bash

# while [ 1 ] ; do aplay file.wav ; done

PIDFILE=/tmp/wplay.pid

# stop
if [[ -f $PIDFILE ]] ; then
    # kill all process and the childs
    # kill -SIGTERM -- -`cat $PIDFILE`
    kill `cat $PIDFILE`
    pkill aplay
else
    echo $$ | tee $PIDFILE
    while [ 1 ] ; do
        aplay '/home/ardi/Music/work/NoisesDotOnline_FileRequest#1604892869611.wav'
    done
fi

rm -v $PIDFILE
